version: '3'
services:
  bind9:
    container_name: dns-demo2
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=America/New_York
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
    networks:
      dns:
        ipv4_address: 192.168.15.10  # Specify the desired IPv4 address for the container

networks:
  dns:
    external:
      name: dns
