---
- name: Configure iptables for DNS server
  hosts: 172.16.21.115 , 172.16.21.66 
  become: yes  # Use sudo to execute commands as root

  tasks:
    - name: Set default policies to DROP
      shell: iptables -P INPUT DROP
      ignore_errors: yes

    - name: Set default policies to DROP
      shell: iptables -P OUTPUT DROP
      ignore_errors: yes
    - name: Set default policies to DROP
      shell: iptables -P FORWARD DROP
      ignore_errors: yes
    - name: statefull connections
      shell:  iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
      ignore_errors: yes

    - name: statefull connections
      shell:  iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED -j ACCEPT
      ignore_errors: yes
      
    - name: Allow incoming DNS traffic (UDP)
      shell: iptables -A INPUT -p udp --dport 53 -j ACCEPT
      ignore_errors: yes

    - name: Allow incoming DNS traffic (TCP)
      shell: iptables -A INPUT -p tcp --dport 53 -j ACCEPT
      ignore_errors: yes
      
    - name: Allow incoming source DNS traffic (TCP)
      shell: iptables -A OUTPUT -p tcp --sport 53 -j ACCEPT
      ignore_errors: yes
    - name: Allow incoming source DNS traffic (UDP)
      shell: iptables -A OUTPUT -p udp --sport 53 -j ACCEPT
      ignore_errors: yes

    - name: Allow loopback traffic
      shell: iptables -A INPUT -i lo -j ACCEPT
      ignore_errors: yes

    - name: Allow loopback traffic
      shell: iptables -A INPUT -i lo -j ACCEPT
      ignore_errors: yes
  
    - name: Allow forwarding of DNS traffic (UDP)
      shell: iptables -I FORWARD -p udp --dport 53 -j ACCEPT
      ignore_errors: yes

    - name: Allow forwarding of DNS traffic (UDP)
      shell: iptables -I FORWARD -p udp --sport 53 -j ACCEPT
      ignore_errors: yes

    - name: Allow forwarding of DNS traffic (TCP)
      shell: iptables -I FORWARD -p tcp --dport 53 -j ACCEPT
      ignore_errors: yes

    - name: Allow forwarding of DNS traffic (TCP)
      shell: iptables -I FORWARD -p tcp --sport 53 -j ACCEPT
      ignore_errors: yes
    - name: Allow forwarding of DNS traffic (TCP)
      shell: iptables -I FORWARD -p tcp --sport 53 -j ACCEPT
      ignore_errors: yes
    - name: Allow SSH
      shell: iptables -A INPUT -p tcp --dport 22 -s 172.16.21.80/28 -j ACCEPT
      ignore_errors: yes
    - name: Allow SSH
      shell: iptables -A INPUT -p tcp --sport 22 -j ACCEPT
      ignore_errors: yes
    - name: Allow ICMP
      shell: iptables -A INPUT -p icmp -j ACCEPT && iptables -A OUTPUT -p icmp -j ACCEPT
      ignore_errors: yes



  