version: '3'
services:
  mattermost:
    image: mattermost/mattermost-team-edition:latest
    networks:
      LAN:
        ipv4_address: 172.16.21.21
    volumes:
      - ./config:/mattermost/config
      - ./data:/mattermost/data
      - ./logs:/mattermost/logs
    environment:
      - MM_SERVICESETTINGS_SITEURL=http://172.16.21.21:8065
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser-password@db/mattermost?sslmode=disable&connect_timeout=10
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser-password
      - POSTGRES_DB=mattermost
    networks:
      - LAN
